# -*- coding: utf-8 -*-
"""EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ou8j0x4bdmpvLPKY7AytwU26GLT3Wm2_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/weather_classification_data.csv")
df

print(df.info())

print(df.head())

print(df.shape)

print(df.isnull().sum())

print(df.duplicated().sum())

print(df.dtypes)

print(df.describe().T)

cat_cols = df.select_dtypes(include=['object']).columns
for col in cat_cols:
      print(df[col].value_counts())

corr = df.corr(numeric_only=True)
print(corr)

plt.figure(figsize=(10,6))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

num_cols = df.select_dtypes(include=np.number).columns
df[num_cols].hist(figsize=(12,8), bins=20, edgecolor='black')
plt.suptitle("Distribution of Numeric Variables", fontsize=16)
plt.show()

for col in num_cols:
    plt.figure(figsize=(6,3))
    sns.boxplot(x=df[col])
    plt.title(f"Boxplot of {col}")
    plt.show()

sns.pairplot(df[num_cols])
plt.suptitle("Pairplot of Numeric Columns", y=1.02)
plt.show()

target_col = "Weather Type"

if target_col in df.columns:
    print("\n===== TARGET VARIABLE DISTRIBUTION =====")
    print(df[target_col].value_counts())

    sns.countplot(x=df[target_col])
    plt.title("Distribution of Target Variable")
    plt.xticks(rotation=45)
    plt.show()

if target_col in df.columns:
    for col in num_cols:
        plt.figure(figsize=(6,4))
        sns.boxplot(x=df[target_col], y=df[col])
        plt.title(f"{col} vs {target_col}")
        plt.show()